import os
import re
import sys
import glob
from google import genai

# Load environment variables from .env file if it exists
env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
if os.path.exists(env_path):
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, val = line.split("=", 1)
                os.environ[key.strip()] = val.strip().strip('"').strip("'")

# Setup Gemini API Key
API_KEY = os.environ.get("GEMINI_API_KEY")
if not API_KEY:
    print("[!] ERROR: GEMINI_API_KEY is not set.")
    sys.exit(1)

client = genai.Client(api_key=API_KEY)

def generate_cover_prompt(outline_content: str) -> str:
    """Ask Gemini to generate a rich, safety-compliant English prompt for Imagen 3."""
    print("    [*] Asking Gemini to write an optimized Imagen 3 prompt...")
    system_instruction = (
        "You are an expert art director and book cover illustrator. "
        "Analyze the provided Thai novel outline and write a highly detailed image generation prompt in English. "
        "The prompt must be safety-compliant (PG-13, no blood, no gore, no violence, no self-harm). "
        "Focus on atmosphere, lighting, art style, key fantasy/mystery elements, and mood. "
        "Specify the style as digital art, cinematic lighting, book cover style, with no text/words on the image. "
        "Return ONLY the prompt text, without quotes, introductions, or formatting."
    )
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=f"Novel Outline:\n{outline_content}",
        config={"system_instruction": system_instruction}
    )
    
    prompt = response.text.strip()
    # Clean up any potential markdown code blocks or quotes
    prompt = re.sub(r"^```\w*\n", "", prompt)
    prompt = re.sub(r"\n```$", "", prompt)
    prompt = prompt.strip('"\'')
    print(f"    [Prompt] {prompt[:120]}...")
    return prompt

def generate_book_cover(prompt: str, output_path: str) -> bool:
    """Generate 1:1 cover image using Imagen 4.0 and save to file."""
    print(f"    [*] Calling Imagen 4.0 to generate cover art...")
    try:
        result = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=dict(
                number_of_images=1,
                output_mime_type="image/jpeg",
                aspect_ratio="1:1"
            )
        )
        
        if not result.generated_images:
            print("    [!] No images generated by Imagen 3.")
            return False
            
        image_bytes = result.generated_images[0].image.image_bytes
        with open(output_path, "wb") as f:
            f.write(image_bytes)
        print(f"    [+] Saved cover art to: {output_path}")
        return True
    except Exception as e:
        print(f"    [!] Error generating cover with Imagen 3: {e}")
        return False

def process_covers(second_brain_dir: str):
    """Scan outlines directory and generate missing book covers."""
    outlines_dir = os.path.join(second_brain_dir, "02_Concept_Extraction")
    covers_dir = os.path.join(second_brain_dir, "05_Active_Projects", "Covers")
    os.makedirs(covers_dir, exist_ok=True)
    
    outline_files = glob.glob(os.path.join(outlines_dir, "*_Outline.md"))
    print(f"[*] Found {len(outline_files)} outlines in Second Brain.")
    
    processed_count = 0
    for filepath in outline_files:
        filename = os.path.basename(filepath)
        clean_title = filename.replace("_Outline.md", "")
        cover_path = os.path.join(covers_dir, f"{clean_title}_Cover.jpg")
        
        # Check if cover already exists
        if os.path.exists(cover_path):
            print(f"[*] Cover already exists for {clean_title}, skipping.")
            continue
            
        print(f"\n[*] Generating cover for: {clean_title}")
        with open(filepath, "r", encoding="utf-8") as f:
            outline_content = f.read()
            
        image_prompt = generate_cover_prompt(outline_content)
        success = generate_book_cover(image_prompt, cover_path)
        if success:
            processed_count += 1
            
    print(f"\n[+] Cover generation process finished. Created {processed_count} covers.")

if __name__ == "__main__":
    second_brain_path = "./SecondBrain"
    if len(sys.argv) > 1:
        second_brain_path = sys.argv[1]
        
    process_covers(second_brain_path)
